자동차 경주 첫 번째 구현
ChoiWonYu/java-racingcar pull request #1
Opened 2023-09-27 10:39 UTC by ChoiWonYu

2023-09-27 15:01 UTC, sosow0212 requested changes
첫 구현치고 많은 노력을 한 것이 정말 눈에 보입니다!

객체지향적으로 설계하려는 모습이 인상적인데요. 코멘트 확인해보시고 조금 더 다듬어주시면 좋을 것 같아요~

먼저 한 번 정리하시고, 두 번째 리뷰부터는 더욱 상세한 리뷰 들어가겠습니다!

2023-09-27 15:01 UTC, sosow0212 commented on src/test/java/type/CarListTest.java
> +import static org.junit.jupiter.api.Assertions.*;
여기도 import에서 와일드카드가 사용되네요

인텔리제이 와일드카드 설정이 있는데 검색해보시면 좋을 것 같아요~

2023-09-30 04:49 UTC, ChoiWonYu commented on src/test/java/service/StubRandom.java
> +public class StubRandom extends Random {
말씀해주신대로 랜덤 값으로 인한 문제 때문에 생성한 객체가 StubRandom인데요

RandomMovingManager 클래스에서 랜덤값을 생성하는 역할의 객체를 주입받고 있습니다. 그 이유는 RandomMovingManager에서 랜덤값을 생성하는 메서드는 아래와 같은데
`    private int generateRandomNumber() {
        return random.nextInt(MAX_RANDOM_NUM+1);
    }
`
기본 random의 nextInt 메서드는 제가 조작할 수 없기 때문에 랜덤한 숫자를 반환하는 역할의 객체를 주입받기로 결정한 것입니다.

그래서 StubRandom 객체는 java.util.Random의 역할을 대신하는 객체이고, 필요한 nextInt 메서드만 오버라이딩 해서 사용하려고 했습니다.

전략 패턴을 아직 공부해보지 않아서.. 공부해보고 다시 설계해보겠습니다!

2023-09-30 06:07 UTC, ChoiWonYu commented
첫 번째 리팩토링
- [ ] 주석 삭제
- [ ] 접근 제한자 수정
- [ ] 상수화를 통한 의미부여
- [ ] 와일드 카드 수정
- [ ] 정적 팩토리 메서드 활용
- [ ] 범용적인 사용을 위해 원시값 포장 네이밍 수정
- [ ] 객생체 4번, 개행 관련 컨벤션 숙지

- carList
    - [ ] 변수명 수정
    - [ ] 초기 생성 과정
    - [ ] 우승자 선정시 재활용 고민 
- [ ] MVC 패턴 적용
    - [ ] View 역할 확실하게 분리
    - [ ] Controller 도입
- [ ] 전략 패턴 적용

2023-09-30 06:09 UTC, ChoiWonYu commented on src/main/java/type/Car.java
> +package type;
여러 객체를 한 개념으로 추상화할 수 있는 클래스들이라고 생각해서 이렇게 지었는데 고민하고 수정해보겠습니다!

2023-09-30 06:12 UTC, ChoiWonYu commented on src/main/java/service/RandomMovingManager.java
> +public class RandomMovingManager implements MovingManager{
이유는 아래 작성한 코멘트와 같습니다!

2023-10-01 04:49 UTC, ChoiWonYu commented
첫 구현에서는 객체에게 요청을 보낼 때 캡슐화를 깨지 않고, 수신자가 행동을 하도록 하는 것에 너무 중점을 두다보니 각자 담당하는 책임이 모호해졌다는 느낌을 받았습니다. 따라서  이번 리팩토링 때 각 객체가 본인의 역할에 충실할 수 있도록 설계하려고 노력했습니다.

먼저 컨트롤러와 DTO를 이용해 도메인과 View의 연관을 끊어내려고 노력했습니다. 도메인은 관련 객체에 대한 비즈니스 로직만을, View는 입출력만을 담당하도록 설계했습니다. 하지만 이 과정에서 캡슐화가 지켜지지 못했고, 전략 패턴도 아직은 조금 어색한 구조로 적용된 것 같습니다.

2023-10-01 04:55 UTC, ChoiWonYu commented on src/main/java/type/CarList.java
> +    public void actOnEachCar(Consumer<Car> action) {
이 부분은 각 자동차를 순회하며 행동하는 것을 Consumer로 받아 stream으로 사용하려고 했는데, 결국 각 자동차 마다 실행해야 하는 로직은 외부에서 주는 것이 아닌 Cars에서 가지고 있어야 한다고 생각이 되어 수정했습니다!

2023-10-01 05:01 UTC, ChoiWonYu commented on src/main/java/type/CarList.java
> +    public Integer getMaxValue() {
테스트 코드에서 해당 메서드를 테스트해야 할 때는 어떻게 하면 좋을까요?

2023-10-01 05:02 UTC, ChoiWonYu commented on src/main/java/type/CarName.java
> +            ExceptionHandler.printErrorMessage(String.format("이름은 %d자 이하만 가능합니다.",MAX_LENGTH));
final 키워드 수정했습니다!

2023-10-01 05:07 UTC, ChoiWonYu commented on src/main/java/RacingGame.java
> +    }
감사합니다 Cars 객체로 해당 로직 옮겼습니다!

2023-10-01 05:08 UTC, ChoiWonYu commented on src/main/java/RacingGame.java
> +        printNewLine();
View의 역할이 최대한 분리되도록 수정했습니다!

2023-10-01 05:09 UTC, ChoiWonYu commented on src/main/java/type/CarName.java
> +public class CarName {
감사합니다 Name으로 수정했습니다!

2023-10-01 05:10 UTC, ChoiWonYu commented on src/main/java/RacingGame.java
> +    private List<Car> generateCars(List<CarName> carNames) {
dto를 만들어서 cars를 생성하도록 수정했습니다!

2023-10-01 05:11 UTC, ChoiWonYu commented on src/test/java/type/CarListTest.java
> +        Car car1 = new Car(name1);
cars가 비어있을 때도 테스트를 해야 해서 BeforeEach는 사용하지 않았습니다 감사합니다!

2023-10-01 05:12 UTC, ChoiWonYu commented on src/main/java/view/InputView.java
> +            .map(CarName::new).collect(Collectors.toList());
dto를 만들어 수정해봤습니다 감사합니다!

2023-10-01 05:12 UTC, ChoiWonYu commented on src/main/java/type/Car.java
> +    public void printCarsMove() {
뷰와 도메인의 의존관계를 최대한 끊는 것에 집중해 수정했습니다 감사합니다!

2023-10-02 05:46 UTC, sosow0212 requested changes
개행과 정렬은 습관화 해주세요 코드 보기가 너무 힘듭니다 ㅠ
몇 부분만 고쳐주세요~

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/RacingMain.java
> +        RacingGameController gameController=RacingGameController.of(CarNamesRequest.from(carNames),
이렇게 하신 이유가 있을까요?
MVC 패턴이 무엇일까요!

정렬도 같이 해주세요~

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/controller/RacingGameController.java
> +    private RacingGameController(final Cars cars,final TryCount tryCount) {
개행 하나 추가해주시고 마지막에 정렬하는 습관도 가져주면 더 좋을 것 같습니다~

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/controller/RacingGameController.java
> +        printEachCarMove(targetCars);
이 부분은 어떤 MVC에서 어떤 객체가 맡아야하는 부분일까요?
해당 코드처럼 하신 이유가 궁금합니다!

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/controller/RacingGameController.java
> +            .getJoinedCarNames();
이 부분도 `CarNameResponse`로 만들고 다시 get으로 꺼내는 이유가 있나요?

`Cars` 객체 안에서 해결하는 방법은 없을까요?

그리고 `getJoinedCarNames`는 `String winners`를 반환해줘야할까요? 아니면 `List<String> winners`를 반환해야할까요?

외부의 view에 대해 어떻게 view를 render하는지 해당 객체가 알 수 있을까요?

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/controller/dto/CarNamesRequest.java
> +    public static final String NAME_SEPARATOR=",";
1. 정렬해주세요
2. 둘 사이 개행 추가해주세요

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/controller/dto/CarNamesRequest.java
> +    public Cars createCars() {
1. 지금 패키지가 dto로 되어있는데, dto에서 객체를 만들어서 반환해주나요? dto의 정의를 한 번 보시면 좋을 것 같습니다. dto에서 로직은 최대한 지양하는 편입니다.

2. dto 없이는 이를 구현할 방법이 없을까요? 너무 복잡하게 문제를 해결하는 것 같아 보입니다 ㅠ

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/controller/dto/TryCountRequest.java
> +    public static TryCountRequest from(final String countInput) {
tryCount에 대해선 예외 검증이 필요 없을까요!

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/domain/Car.java
> +        this.moveCount = new MoveCount(DEFAULT_MOVE_COUNT_VALUE);
`MoveCount(...)`를 넣어주는 걸 정적 팩토리 메서드에서 수행하고, 해당 생성자는 기본 생성자의 역할을 하는 건 어떨까요?
그럴 때 장점이 무엇일까요?

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/domain/Car.java
> +        return countValue.equals(value);
객체지향적으로 수행되지 않고 있습니다.

`this.moveCount.isSameValue()`와 같은 형식이 되어야하지 않을까요?
`getter`를 통해 값을 꺼내오고, 그 값을 외부에서 비교해주는 건 캡슐화가 이뤄지지 않는 것 같아요

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/domain/Cars.java
> +    private final MovingStrategy movingManager;
일급 컬렉션에는 List<Car>만 있어야하지 않을까요?
MovingStrategy를 다른 곳에 두고 사용할 방법은 없을까요?

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/service/RandomMovingStrategy.java
> +    public final int    MAX_RANDOM_NUM=9;
이 부분도 정렬 해주세요

2023-10-02 05:46 UTC, sosow0212 commented on src/main/java/view/InputOutputView.java
> +public class InputOutputView {
이 부분도 Input, Output을 나눠서 역할을 분담해주세요

2023-10-02 05:46 UTC, sosow0212 commented on src/test/java/service/RandomMovingStrategyTest.java
> +    void when_num_smaller_than_4_return_false() {
`given - when - then 패턴` 사용해주세요~

2023-10-02 12:54 UTC, ChoiWonYu commented
두 번째 리팩토링

- [ ] 정렬, 개행
- [ ] MVC 패턴 다시 적용
- [ ] dto 다시 고려
- [ ] tryCount 유효성 검사
- [ ] moveCount 관련 로직은 해당 객체로 분리
- [ ] Cars에서 다른 객체 의존하지 않도록 리팩토링
- [ ] Input,Output 분리
- [ ] given-when-then 패턴 사용

2023-10-03 06:48 UTC, ChoiWonYu commented on src/main/java/domain/Car.java
> +        this.moveCount = new MoveCount(DEFAULT_MOVE_COUNT_VALUE);
Car에 대해 다양한 생성 방법을 얻을 수 있을 것 같아요 수정했습니다 감사합니다!

2023-10-03 08:53 UTC, ChoiWonYu commented on src/main/java/controller/dto/CarNamesRequest.java
> +    public Cars createCars() {
status만 남기고 dto는 모두 삭제했습니다 감사합니다!

2023-10-03 08:54 UTC, ChoiWonYu commented on src/main/java/RacingMain.java
> +        RacingGameController gameController=RacingGameController.of(CarNamesRequest.from(carNames),
수정했습니다 감사합니다!

2023-10-03 08:57 UTC, ChoiWonYu commented on src/main/java/controller/RacingGameController.java
> +        printEachCarMove(targetCars);
printEachCarMove가 각 car의 상태를 출력하는 것이 아닌 cars를 순회하면서 
뷰에게 각 car의 상태를 출력하라고 전달해주는 메서드인데 메스드명이 잘못된 것 같아 수정했습니다!

2023-10-03 09:05 UTC, ChoiWonYu commented
Controller에 대한 개념이 아직 제대로 안 잡힌 것 같습니다.
> Model과 View의 중간 다리, 본 프로젝트 같은 경우엔 사용자의 입력을 받아 그 요청을 Model과 View에 반영하는 역할
> 때문에 비즈니스 로직이나 직접적인 View에 대한 관여를 해서는 안 된다.
정도로 정리가 됐는데 이게 맞는지 궁금합니다.

또한 View에서 출력을 할 때 Model에서 도메인을 출력 포맷에 맞게 변형해야 하는 로직은 어디서 처리해야 하는지 궁금합니다.
dto로 변한해야 할 때 이 로직을 Model에서 수행하면 View에 출력하는 포맷을 알게 되는 것이 되고, View에서 수행하면 결국 도메인의 타입을 아는 것이 되니 별도의 Mapper 클래스로 위 작업을 수행했는데 이 방법도 좀 아닌 것 같아서 어떤 방법이 좋은 방법인지 궁금합니다!

2023-10-03 09:34 UTC, sosow0212 requested changes
엄청난 성장을 하셨네요 ㅎㅎ 아마도 해당 단계에서 마지막 리뷰가 될 것 같아요
조금 더 고민하고 구조적으로 고민해보는 건 어떨까요?

리팩토링을 할 때 A를 바꾸면 B, C, D도 같이 바뀌는지 고민을 해보고 어떻게 하면 유지보수에 효율적인지 고민해보는 시간을 가지면 좋을 것 같습니다.

처음에 비해서 코드도 훨씬 읽기 좋고 객체지향적으로 변하는 모습이 많이 공부했음이 느껴지네요
수고하셨습니다 👍

---- 질문 답변

> 또한 View에서 출력을 할 때 Model에서 도메인을 출력 포맷에 맞게 변형해야 하는 로직은 어디서 처리해야 하는지 궁금합니다. dto로 변한해야 할 때 이 로직을 Model에서 수행하면 View에 출력하는 포맷을 알게 되는 것이 되고, View에서 수행하면 결국 도메인의 타입을 아는 것이 되니 별도의 Mapper 클래스로 위 작업을 수행했는데 이 방법도 좀 아닌 것 같아서 어떤 방법이 좋은 방법인지 궁금합니다

해당 부분도 컨트롤러 Status쪽 리뷰에 남겨있는데요 혹시나 보고 이해가 안된다면 DM 주세요 :)

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/RacingGameController.java
> +    private final Scanner reader;
해당 부분도 InputView로 빼서 입력 받는 부분을 모두 해당 클래스에 위임하는 것도 좋아보입니다!

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/RacingGameController.java
> +        this.cars = CarMapper.inputToCars(namesInput);
Mapper의 역할이 정적팩토리메서드 같은데, 따로 Mapper를 만드신 이유가 있나요?
이건 단지 궁금해서요 ㅎㅎ

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/RacingGameController.java
> +        OutputView.showCarMove(status.getCarName(), status.getCountMove());
dto를 통해서 해당 로직과 같이 수행해도 되지만 결과적으로 CarStatus는 dto의 역할을 하네요!

지금도 서로 의존적이지 않아서 좋지만
`OutputView.showCarMove(car.getName(), car.getMoveCount());`로 한다면 컨트롤러만 연결다리 역할로 둘을 연결시켜줄 수 있을 것 같아요 (CarStatus가 굳이 필요 없다는 뜻입니다!)

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/service/RandomMovingStrategy.java
> +        return randomNumber >= MAX_RANDOM_NUM / 2;
해당 객체는 랜덤 수를 뽑아주는 역할을 하면서 Car가 이동할 수 있는지도 판단하나요?
그렇다면 Car에 의존적인 객체일까요?

RandomMovingStrategy 객체만 봤을 땐 랜덤한 수를 반환해주는 것 같은데
return에서 사용되는 로직은 다른 부분에서 처리해주는게 좋지 않을까요?

Car의 이동 전략이 바뀐다면 당연히 Car 부분에서 리팩토링을 진행할 것 같은데, 이런 구조라면 리팩토링할 때 해당 객체도 확인해봐야할 것 같습니다

2023-10-03 09:34 UTC, sosow0212 commented on src/test/java/domain/CarNameTest.java
> +        //given
```suggestion
        // given
```
다른 부분도 한 칸 씩 띄워주는게 가독성에서 좋은 것 같아요 ㅎㅎ 귀찮다면 다음 미션부터!

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/exception/ErrorMessage.java
> +    LONGER_THAN_MAX_NAME_LENGTH(String.format("이름은 %d자 이하만 가능합니다.", Name.MAX_LENGTH)),
개행 한 칸 추가해주세요

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/domain/Cars.java
>      }
오 이제 뭔가 일급컬렉션의 느낌이 술술 나는데요? 👍

한 가지 궁금한 건 현재 자동차가 움직일지 아닐지 판단은 Car 안에서 하고 있는 것 같아요.
그렇다면 현재 구조라면 모든 Car 객체가 Random값을 주는 객체를 가지고 있어야하나요?

Cars에서 forEach를 통해서 Random 값을 생성한 후에 이 랜덤 값을 `Car.move(int number)` 와 같이 주면 무엇이 좋을까요?
혹은 `Car.move(boolean canMove)`와 같이 줄 땐 뭐가 다를까요?

둘은 비슷해보이지만 미묘하게 다른데, 어떻게 다른 것 같은지 의견을 남겨주세요 ㅎㅎ

또한 Cars에서 랜덤 값을 미리 뽑아서 매개변수로 이 값을 넘겨준다면 테스트하기 더 편하지 않을까요?
지금 구조에서는 `Car.move()`를 테스트할 때 랜덤 값 때문에 FIRST 원칙 중 R이 위배될 것 같아요

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/domain/Car.java
>      }
오 둘은 각각 어디서 사용하나요?
위에 리뷰 참고하면 하나로 합칠 수 있을 것 같아요

DEAFULT_MOVE_COUNT_VALUE와 같이 기본 생성 전략이라면 메서드 명을 of, from 보다는 createDefault와 같이 줘도 좋을 것 같습니다~

정적 팩토리 메서드에서 of, from 등등 암묵적인 네이밍도 좋지만 이름을 통해 어떤 생성 전략인지 의미를 주는 것도 하나의 사용 이유겠죠?

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/domain/Cars.java
>              .collect(Collectors.toList());
방어적 복사를 통해 반환해보는 건 어떨까요?
만약 외부에서 getWinners를 통해 List 내부의 객체를 건든다면 값이 바뀔 수 있지 않을까요?

2023-10-03 09:34 UTC, sosow0212 commented on src/main/java/domain/Cars.java
> +    public void actEachCar(Consumer<Car> act) {
Consumer까지 사용하다니 그동안 많이 공부했군요~

2023-10-03 09:34 UTC, sosow0212 commented on src/test/java/domain/TryCountTest.java
> +
불필요한 개행 제거!

2023-10-03 16:49 UTC, ChoiWonYu commented on src/main/java/RacingGameController.java
> +        this.cars = CarMapper.inputToCars(namesInput);
사실 Mapper에 대한 고민 때문에 질문을 드린 것이었는데 현재 Mapper는 정적 팩토리 메서드의 역할이긴 하지만, 저는 입력값에서 Car를 구분하는 NAME_SEPARATOR를 알고 있다는 점에서 이 로직을 분리해야 한다고 생각했습니다. 

만약 Cars의 정적 팩토리 메소드에서 위 구분자를 알고 있다는 것은 View에 대해 알고 있는 것이라고 판단했습니다. 이처럼 View에서 Model의 변환이나 Model에서 View로의 변환을 담당하는 역할의 객체가 있어야 한다고 생각해서 만든 객체입니다!

하지만 이 부분이 어색해보여서 다른 좋은 방법이 있을까 궁금했습니다!

2023-10-03 17:06 UTC, ChoiWonYu commented on src/main/java/domain/Cars.java
>              .collect(Collectors.toList());
그런 문제가 발생할 수 있겠군요..! 지금은 단순히 출력하는 용도의 반환뿐이니 복사 관련 개념을 공부하고,
다음에 필터링한 객체를 수정하는 등의 로직이 있을 때 적용해보겠습니다! 감사합니다!

2023-10-03 17:15 UTC, ChoiWonYu commented on src/main/java/service/RandomMovingStrategy.java
> +        return randomNumber >= MAX_RANDOM_NUM / 2;
이것도 메서드 이름을 제가 헷갈리게 적어서 생긴 문제 같네요..
이름 그대로 해당 객체는 랜덤으로 이동 전략을 구현하는 구현체이기 때문에 Car에 의존하고 있지는 않다고 생각합니다!

2023-10-03 17:25 UTC, ChoiWonYu commented on src/main/java/domain/Cars.java
>      }
제가 이전 구현에 Cars에 MovingStrategy를 멤버로 가지게 했었는데 일급 컬렉션에 다른 멤버가 있는 게 어색한 것 같다는 피드백도 있었고, 말그대로 이동 전략이기 때문에 각 Car에서 이를 가지고 있는 게 자연스럽다고 생각해서 Car에 이동 전략 객체를 멤버로 가지게 했습니다!

말씀해주신 것처럼 결국 Car에서 Random 값을 주는 객체가 있는 것은 맞지만 Random 값을 생성하는 것은 이동 전략 중 하나인 RandomStrategy이기 때문에 저는 Car에서 Random값을 생성한다기보다는 Car가 가지고 있는 이동 전략인 RandomStrategy에서 random값을 생성한다가 더 자연스럽다고 생각했는데 어떻게 생각하시나요??

따라서 Car는 전진 전략의 canMove 메서드가 true를 반환할 때 전진해야하고,
RandomStrategy는 조건에 맞는 난수가 생성됐을 때 canMove 메서드로 true를 반환해야 한다.
위처럼 테스트를 진행했는데 여기에 대한 의견도 궁금합니다!

2023-10-03 17:34 UTC, ChoiWonYu commented
피드백 최대한 반영해서 리팩토링 진행했습니다! 이번 리팩토링에서도 복사에 관한 개념 등 많이 배운 것 같습니다
피드백 해주신 부분 중 의문점이 몇가지 있어 코멘트 남겼는데 의견 부탁드립니다 감사합니다!

2023-10-04 04:49 UTC, sosow0212 commented on src/main/java/RacingGameController.java
> +        this.cars = CarMapper.inputToCars(namesInput);
ㅎㅎ 좋습니다
정답은 없지만 Cars 내부에서 한다면 `,`즉 뷰를 알아야한다는 이유 때문에 책임을 분리하신거군요
좋은 의도 같아요~

2023-10-04 04:52 UTC, sosow0212 commented on src/main/java/service/RandomMovingStrategy.java
> +    public final int MAX_RANDOM_NUM = 9;
생각하신 것처럼 저도 범용적이라면 ENUM으로 따로 분리를 하는 편입니다
하지만 해당 클래스에서만 사용하고 범용적이지 않다면 클래스 안에서 선언을 하는 편이 오히려 직관적이기 때문에 좋은 것 같아요.

다른 클래스에서 해당 클래스의 상수를 이용하는 것이라면 차라리 ENUM으로 분리를 하면 어떨까요?
타 클래스의 상수에 접근하는 것은 의존하는 것이기 때문에 좋지 않아 보입니다. (퇴보된 클래스 즉 상수만을 모은 클래스라면 어느정도 납득은 되겠지만 이펙티브 자바에서도 상수만을 모아둔 퇴보된 클래스는 지양하라고 나와있어서 범용적이면 ENUM으로 관리하시면 될 것 같습니다!)

2023-10-04 04:55 UTC, sosow0212 commented on src/main/java/service/RandomMovingStrategy.java
> +        return randomNumber >= MAX_RANDOM_NUM / 2;
`randomNumber >= MAX_RANDOM_NUM / 2;` 이 부분은 Car의 이동 전략을 알아야 사용할 수 있는 표현 같아서요~

랜덤한 수를 뽑아주는 전략에서는 제 생각에는 만약 확장된다면 구현체마다 랜덤한 수의 범위를 결정짓는 것 밖에 하지 못한다고 생각이 듭니다. 예를 들면 StrategyImpl1 에선 1~10의 랜덤, StrategyImpl2 에선 1~500의 랜덤 수 이런식으로요

`canCarMove()`는 결국 랜덤한 수를 뽑아주면서 차량의 이동 전략까지 알고서 움직일 수 있는지 판단을 해주는 것인데 이 부분이 저는 의존적이라고 생각이 듭니다

그리고 두 가지의 역할을 수행해서 다른 객체가 수행할 수 있는 것을 해당 객체가 수행한다고 생각이 들어서 남긴 코멘트입니다!

2023-10-04 04:57 UTC, sosow0212 approved these changes
수고하셨습니다!
질문하신 부분에 대해 코멘트 남겼습니다~

객체지향적으로 설계하려는 모습이 너무 좋았고 잘 하신 것 같아서 approve 하겠습니다.
다만 몇 부분은 수정할 필요가 있다고 생각하는데, 다음 미션에서 같이 리뷰할게요 ㅎㅎ 고생하셨습니다

2023-10-04 04:57 UTC, sosow0212 commented on src/main/java/view/InputView.java
> +        this.reader=reader;
정렬이 안 되어있습니다!

2023-10-04 07:37 UTC, ChoiWonYu commented on src/main/java/service/RandomMovingStrategy.java
> +        return randomNumber >= MAX_RANDOM_NUM / 2;
아하 이해됐습니다 다시 설계해보겠습니다!

2023-10-04 17:12 UTC, merged